services:
  - type: web
    name: shiksha-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ShikshaAi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ShikshaAi.settings
      - key: SECRET_KEY
        generateValue: true
